### ISSUE TITLE
GPL issue

### ISSUE THREAD

**Issue by carlkl** [cosmo-ethz/hope#34]
Is it possible to relax the license to a MIT or BSD like license - at least for the runtime code that is included into the users python programm and extensions?

**Comment by cosmo-ethz** [comment]
I’ll check with the co-authors to see what they think and as soon as I know more I’ll get back to you.

**Comment by cosmo-ethz** [comment]
@carlkl,  Since HOPE has been developed at a publicly funded university we think that GPL is an adequate choice for the licensing. 
Or could you provide me a good reason why MIT or BSD would be better?

**Comment by carlkl** [comment]
@cosmo-ethz <https://github.com/cosmo-ethz> , the complete scipy-stack is
based on opensource code without copyleft licenses. The liberal license is
one of the attractions of Python anyway.
HOPE could be a potential sucessor of scipy-weave IMHO. I got the hope,
that at least the generated code could be distributed without copyleft.

2015-01-20 10:47 GMT+01:00 cosmo-ethz <notifications@github.com>:

**Comment by cosmo-ethz** [comment]
@carlkl Afaik, data that is produced with a certain software does normally not underlie the license of this software. In the case of HOPE, the code that is generated during the JIT compilation could be seen as data. Hence, it would not be under GPL.

**Comment by carlkl** [comment]
@cosmo-ethz <https://github.com/cosmo-ethz>, there is some more code from
the hope package, that is incorporated into users code base during code
generation and depoyment. This should be considered as well.

2015-01-23 15:46 GMT+01:00 cosmo-ethz <notifications@github.com>:
